"""
AI Race Commentary Window — Displays a live feed of detected race events
with colour-coded commentary, icons, and premium dark-glass styling.
Also provides a one-click AI-generated race summary report.
"""

import sys
import threading
from PySide6.QtWidgets import (
    QApplication, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QScrollArea, QFrame, QSizePolicy,
    QPushButton, QTextEdit
)
from PySide6.QtCore import Qt, QPropertyAnimation, QEasingCurve, Signal, QTimer
from PySide6.QtGui import QFont, QColor

from src.gui.pit_wall_window import PitWallWindow
from src.lib.settings import get_settings


# ── Event type styling ───────────────────────────────────────────────────

EVENT_STYLES = {
    "overtake": {
        "icon": "🏁",
        "accent": "#00e676",      # green
        "bg": "rgba(0, 230, 118, 0.08)",
        "label": "OVERTAKE",
    },
    "pit_stop": {
        "icon": "🔧",
        "accent": "#42a5f5",      # blue
        "bg": "rgba(66, 165, 245, 0.08)",
        "label": "PIT STOP",
    },
    "fastest_lap": {
        "icon": "⚡",
        "accent": "#ab47bc",      # purple
        "bg": "rgba(171, 71, 188, 0.08)",
        "label": "FASTEST LAP",
    },
    "safety_car": {
        "icon": "🟡",
        "accent": "#ffa726",      # amber
        "bg": "rgba(255, 167, 38, 0.08)",
        "label": "SAFETY CAR",
    },
}

DEFAULT_STYLE = {
    "icon": "📡",
    "accent": "#78909c",
    "bg": "rgba(120, 144, 156, 0.08)",
    "label": "EVENT",
}


def _fmt_race_time(seconds: float) -> str:
    """Format session seconds as H:MM:SS."""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    return f"{h}:{m:02}:{s:02}"


class EventCard(QFrame):
    """A single event card in the commentary feed."""

    def __init__(self, event: dict, parent=None):
        super().__init__(parent)
        self._event = event          # keep reference for refresh
        self.setObjectName("eventCard")

        style = EVENT_STYLES.get(event.get("type", ""), DEFAULT_STYLE)
        accent = style["accent"]
        bg = style["bg"]

        self.setStyleSheet(f"""
            #eventCard {{
                background: {bg};
                border-left: 3px solid {accent};
                border-radius: 6px;
                padding: 8px 12px;
                margin: 2px 0px;
            }}
            #eventCard:hover {{
                background: rgba(255, 255, 255, 0.06);
            }}
        """)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(8, 6, 8, 6)
        layout.setSpacing(10)

        # Icon
        icon_label = QLabel(style["icon"])
        icon_label.setFont(QFont("Segoe UI Emoji", 18))
        icon_label.setFixedWidth(30)
        icon_label.setAlignment(Qt.AlignCenter)
        layout.addWidget(icon_label)

        # Content column
        content = QVBoxLayout()
        content.setSpacing(2)

        # Header row: type badge + time
        header = QHBoxLayout()
        badge = QLabel(style["label"])
        badge.setFont(QFont("Inter", 9, QFont.Bold))
        badge.setStyleSheet(f"""
            color: {accent};
            background: rgba(255, 255, 255, 0.06);
            border-radius: 3px;
            padding: 1px 6px;
        """)
        header.addWidget(badge)

        lap = event.get("lap", "")
        time_str = _fmt_race_time(event.get("time", 0))
        meta = QLabel(f"Lap {lap}  ·  {time_str}")
        meta.setFont(QFont("Inter", 9))
        meta.setStyleSheet("color: rgba(255, 255, 255, 0.5);")
        header.addWidget(meta)
        header.addStretch()
        content.addLayout(header)

        # Commentary text — prefer AI commentary, fall back to template
        ai_text = event.get("ai_commentary")
        template_text = event.get("commentary", "")
        is_ai = ai_text is not None
        commentary_text = ai_text if is_ai else template_text

        self._commentary_label = QLabel(commentary_text)
        self._commentary_label.setFont(QFont("Inter", 12))
        self._commentary_label.setStyleSheet("color: rgba(255, 255, 255, 0.92);")
        self._commentary_label.setWordWrap(True)
        content.addWidget(self._commentary_label)

        # AI badge if commentary was generated by the LLM
        self._content_layout = content
        self._ai_badge_added = is_ai
        if is_ai:
            self._add_ai_badge(content)

        layout.addLayout(content, 1)

        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)

    def _add_ai_badge(self, content):
        ai_badge = QLabel("🤖 AI")
        ai_badge.setFont(QFont("Inter", 8, QFont.Bold))
        ai_badge.setStyleSheet("""
            color: #ab47bc;
            background: rgba(171, 71, 188, 0.12);
            border-radius: 3px;
            padding: 1px 5px;
        """)
        ai_badge.setFixedWidth(42)
        content.addWidget(ai_badge)

    def refresh_commentary(self):
        """Update the commentary label in-place after AI enrichment."""
        ai_text = self._event.get("ai_commentary")
        if ai_text and ai_text != self._commentary_label.text():
            self._commentary_label.setText(ai_text)
            if not self._ai_badge_added:
                self._add_ai_badge(self._content_layout)
                self._ai_badge_added = True


class AICommentaryWindow(PitWallWindow):
    """PitWallWindow subclass that displays a live AI commentary feed."""

    # Signals for thread-safe summary updates
    _summary_ready = Signal(str)
    _summary_error = Signal(str)
    _enrich_progress = Signal(int, int, int)   # batch_done, total_batches, enriched
    _enrich_done = Signal(dict)                 # stats dict
    _enrich_error = Signal(str)

    def __init__(self, auto_start_client: bool = True):
        self._seen_event_keys: set = set()
        self._event_widgets: list[EventCard] = []
        self._all_race_events: list[dict] = []
        self._all_frames: list[dict] = []
        self._is_generating_summary: bool = False
        self._is_enriching: bool = False
        super().__init__(auto_start_client=auto_start_client)
        self.setWindowTitle("🏎️ AI Race Commentary")
        self.setGeometry(100, 100, 480, 700)

        # Connect signals
        self._summary_ready.connect(self._on_summary_ready)
        self._summary_error.connect(self._on_summary_error)
        self._enrich_progress.connect(self._on_enrich_progress)
        self._enrich_done.connect(self._on_enrich_done)
        self._enrich_error.connect(self._on_enrich_error)

    def setup_ui(self):
        central = QWidget()
        self.setCentralWidget(central)

        main_layout = QVBoxLayout(central)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(0)

        # ── Header ─────────────────────────────────────────────────────
        header = QFrame()
        header.setFixedHeight(90)
        header.setStyleSheet("""
            QFrame {
                background: qlineargradient(
                    x1:0, y1:0, x2:1, y2:0,
                    stop:0 #1a1a2e, stop:1 #16213e
                );
                border-bottom: 1px solid rgba(255,255,255,0.08);
            }
        """)
        h_layout = QVBoxLayout(header)
        h_layout.setContentsMargins(16, 8, 16, 8)

        title_row = QHBoxLayout()
        title = QLabel("🧠 AI Race Commentary")
        title.setFont(QFont("Inter", 18, QFont.Bold))
        title.setStyleSheet("color: white;")
        title_row.addWidget(title)
        title_row.addStretch()

        # Generate Summary button
        self.summary_btn = QPushButton("📋 Generate Summary")
        self.summary_btn.setFont(QFont("Inter", 10, QFont.Bold))
        self.summary_btn.setCursor(Qt.PointingHandCursor)
        self.summary_btn.setFixedHeight(30)
        self.summary_btn.setStyleSheet("""
            QPushButton {
                background: rgba(171, 71, 188, 0.2);
                color: #ce93d8;
                border: 1px solid rgba(171, 71, 188, 0.35);
                border-radius: 8px;
                padding: 0 14px;
                font-size: 10px;
            }
            QPushButton:hover {
                background: rgba(171, 71, 188, 0.35);
                color: white;
                border-color: rgba(171, 71, 188, 0.6);
            }
            QPushButton:disabled {
                background: rgba(255,255,255,0.06);
                color: rgba(255,255,255,0.25);
                border-color: rgba(255,255,255,0.08);
            }
        """)
        self.summary_btn.clicked.connect(self._on_generate_summary)
        title_row.addWidget(self.summary_btn)

        # Enrich Key Events button
        self.enrich_btn = QPushButton("✨ Enrich Key Events")
        self.enrich_btn.setFont(QFont("Inter", 10, QFont.Bold))
        self.enrich_btn.setCursor(Qt.PointingHandCursor)
        self.enrich_btn.setFixedHeight(30)
        self.enrich_btn.setStyleSheet("""
            QPushButton {
                background: rgba(225, 6, 0, 0.15);
                color: #ef9a9a;
                border: 1px solid rgba(225, 6, 0, 0.3);
                border-radius: 8px;
                padding: 0 14px;
                font-size: 10px;
            }
            QPushButton:hover {
                background: rgba(225, 6, 0, 0.3);
                color: white;
                border-color: rgba(225, 6, 0, 0.6);
            }
            QPushButton:disabled {
                background: rgba(255,255,255,0.06);
                color: rgba(255,255,255,0.25);
                border-color: rgba(255,255,255,0.08);
            }
        """)
        self.enrich_btn.clicked.connect(self._on_enrich_key_events)
        title_row.addWidget(self.enrich_btn)

        h_layout.addLayout(title_row)

        subtitle = QLabel("Live event detection & AI-powered analysis")
        subtitle.setFont(QFont("Inter", 10))
        subtitle.setStyleSheet("color: rgba(255,255,255,0.45);")
        h_layout.addWidget(subtitle)

        # Enrich progress bar (hidden by default)
        from PySide6.QtWidgets import QProgressBar
        self.enrich_progress = QProgressBar()
        self.enrich_progress.setFixedHeight(4)
        self.enrich_progress.setTextVisible(False)
        self.enrich_progress.setStyleSheet("""
            QProgressBar { background: rgba(255,255,255,0.05); border-radius: 2px; border: none; }
            QProgressBar::chunk { background: #e10600; border-radius: 2px; }
        """)
        self.enrich_progress.setVisible(False)
        h_layout.addWidget(self.enrich_progress)

        main_layout.addWidget(header)

        # ── Summary panel (hidden by default) ─────────────────────────
        self.summary_panel = QFrame()
        self.summary_panel.setVisible(False)
        self.summary_panel.setStyleSheet("""
            QFrame {
                background: rgba(171, 71, 188, 0.06);
                border-bottom: 1px solid rgba(171, 71, 188, 0.15);
            }
        """)
        sp_layout = QVBoxLayout(self.summary_panel)
        sp_layout.setContentsMargins(14, 10, 14, 10)
        sp_layout.setSpacing(6)

        sp_header_row = QHBoxLayout()
        sp_title = QLabel("📋 AI Race Summary")
        sp_title.setFont(QFont("Inter", 12, QFont.Bold))
        sp_title.setStyleSheet("color: #ce93d8;")
        sp_header_row.addWidget(sp_title)
        sp_header_row.addStretch()

        self.close_summary_btn = QPushButton("✕")
        self.close_summary_btn.setFixedSize(24, 24)
        self.close_summary_btn.setCursor(Qt.PointingHandCursor)
        self.close_summary_btn.setStyleSheet("""
            QPushButton {
                background: rgba(255,255,255,0.06);
                color: rgba(255,255,255,0.5);
                border: none;
                border-radius: 12px;
                font-size: 12px;
            }
            QPushButton:hover {
                background: rgba(255,255,255,0.12);
                color: white;
            }
        """)
        self.close_summary_btn.clicked.connect(
            lambda: self.summary_panel.setVisible(False)
        )
        sp_header_row.addWidget(self.close_summary_btn)
        sp_layout.addLayout(sp_header_row)

        self.summary_text = QTextEdit()
        self.summary_text.setReadOnly(True)
        self.summary_text.setFont(QFont("Inter", 11))
        self.summary_text.setMinimumHeight(120)
        self.summary_text.setMaximumHeight(250)
        self.summary_text.setStyleSheet("""
            QTextEdit {
                background: rgba(0, 0, 0, 0.2);
                color: rgba(255,255,255,0.88);
                border: 1px solid rgba(171, 71, 188, 0.15);
                border-radius: 8px;
                padding: 10px;
                line-height: 1.5;
            }
        """)
        sp_layout.addWidget(self.summary_text)

        main_layout.addWidget(self.summary_panel)

        # ── Stats bar ──────────────────────────────────────────────────
        stats_bar = QFrame()
        stats_bar.setFixedHeight(36)
        stats_bar.setStyleSheet("""
            QFrame {
                background: rgba(255, 255, 255, 0.03);
                border-bottom: 1px solid rgba(255,255,255,0.06);
            }
        """)
        stats_layout = QHBoxLayout(stats_bar)
        stats_layout.setContentsMargins(16, 0, 16, 0)

        self.event_count_label = QLabel("0 events detected")
        self.event_count_label.setFont(QFont("Inter", 10))
        self.event_count_label.setStyleSheet("color: rgba(255,255,255,0.5);")
        stats_layout.addWidget(self.event_count_label)
        stats_layout.addStretch()

        self.filter_label = QLabel("All Events")
        self.filter_label.setFont(QFont("Inter", 10))
        self.filter_label.setStyleSheet("color: rgba(255,255,255,0.4);")
        stats_layout.addWidget(self.filter_label)

        main_layout.addWidget(stats_bar)

        # ── Scrollable event feed ──────────────────────────────────────
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll.setStyleSheet("""
            QScrollArea {
                background: transparent;
                border: none;
            }
            QScrollBar:vertical {
                background: rgba(255,255,255,0.03);
                width: 6px;
                border-radius: 3px;
            }
            QScrollBar::handle:vertical {
                background: rgba(255,255,255,0.15);
                border-radius: 3px;
                min-height: 30px;
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                height: 0px;
            }
        """)

        self.feed_widget = QWidget()
        self.feed_layout = QVBoxLayout(self.feed_widget)
        self.feed_layout.setContentsMargins(12, 12, 12, 12)
        self.feed_layout.setSpacing(6)
        self.feed_layout.setAlignment(Qt.AlignTop)

        # Placeholder
        self.placeholder = QLabel("Waiting for race events…")
        self.placeholder.setFont(QFont("Inter", 13))
        self.placeholder.setStyleSheet("color: rgba(255,255,255,0.3);")
        self.placeholder.setAlignment(Qt.AlignCenter)
        self.feed_layout.insertWidget(0, self.placeholder)

        scroll.setWidget(self.feed_widget)
        self.scroll_area = scroll

        main_layout.addWidget(scroll, 1)

        # ── Apply global dark theme ───────────────────────────────────
        self.setStyleSheet(self.styleSheet() + """
            QMainWindow, QWidget {
                background: #0d1117;
                color: #e6edf3;
            }
        """)

    def on_telemetry_data(self, data: dict):
        """Called every telemetry tick — add new events to the feed."""
        # Track frame data for summary generation
        frame = data.get("frame")
        if frame:
            self._all_frames.append(frame)

        events = data.get("race_events", [])
        if not events:
            return

        # Keep the full event list for summary generation
        self._all_race_events = events

        scroll_bar = self.scroll_area.verticalScrollBar()
        old_scroll_value = scroll_bar.value()
        was_at_bottom = old_scroll_value >= scroll_bar.maximum() - 24

        new_count = 0
        for event in events:
            key = (event.get("type"), round(event.get("time", 0), 1),
                   event.get("driver", ""))
            if key in self._seen_event_keys:
                continue
            self._seen_event_keys.add(key)

            # Remove placeholder on first event
            if self.placeholder.isVisible():
                self.placeholder.hide()

            card = EventCard(event)
            
            self.feed_layout.addWidget(card)
            self._event_widgets.append(card)
            new_count += 1

        if new_count > 0:
            total = len(self._seen_event_keys)
            self.event_count_label.setText(f"{total} events detected")

            if was_at_bottom:
                QTimer.singleShot(0, self._scroll_to_latest_event)
            else:
                QTimer.singleShot(0, lambda value=old_scroll_value: scroll_bar.setValue(value))

    def _scroll_to_latest_event(self):
        """Keep live-follow users on the latest event without landing in empty space."""
        if self._event_widgets:
            self.scroll_area.ensureWidgetVisible(self._event_widgets[-1], 0, 12)


    # ── Summary generation ───────────────────────────────────────────────

    def _on_generate_summary(self):
        """Handle the Generate Summary button click."""
        if self._is_generating_summary:
            return

        if not self._all_race_events:
            self.summary_text.setPlainText(
                "No race events detected yet. Wait for events to appear "
                "in the feed before generating a summary."
            )
            self.summary_panel.setVisible(True)
            return

        settings = get_settings()
        api_key = settings.groq_api_key
        if not api_key:
            self.summary_text.setPlainText(
                "⚠️ No Groq API key configured. Go to Settings to add your key."
            )
            self.summary_panel.setVisible(True)
            return

        # Show panel with loading state
        self._is_generating_summary = True
        self.summary_btn.setEnabled(False)
        self.summary_btn.setText("⏳ Generating…")
        self.summary_text.setPlainText("Generating race summary — this may take a few seconds…")
        self.summary_panel.setVisible(True)

        # Run in background thread
        events_copy = list(self._all_race_events)
        # Use only a sample of frames (first, last, and every 100th)
        frames_sample = []
        if self._all_frames:
            frames_sample.append(self._all_frames[0])
            for i in range(100, len(self._all_frames), 100):
                frames_sample.append(self._all_frames[i])
            frames_sample.append(self._all_frames[-1])

        thread = threading.Thread(
            target=self._generate_summary_thread,
            args=(events_copy, frames_sample, api_key, settings.ai_model),
            daemon=True,
        )
        thread.start()

    def _generate_summary_thread(self, events, frames, api_key, model):
        """Background thread for summary generation."""
        try:
            from src.insights.ai_commentary_engine import AICommentaryEngine
            engine = AICommentaryEngine(
                api_key=api_key,
                model=model or "llama-3.3-70b-versatile"
            )
            summary = engine.generate_race_summary(events, frames)
            if summary:
                self._summary_ready.emit(summary)
            else:
                self._summary_error.emit(
                    "Failed to generate summary. Check your API key and try again."
                )
        except Exception as e:
            msg = str(e)
            if "429" in msg or "RESOURCE_EXHAUSTED" in msg:
                import re
                if "PerDay" in msg or "limit: 20" in msg or "limit: 0" in msg:
                    self._summary_error.emit(
                        "Daily API quota reached (free tier limit).\n\n"
                        "Options:\n"
                        "• Wait until tomorrow — quota resets daily\n"
                        "• Enable billing at aistudio.google.com/apikey for 1,500 requests/day free"
                    )
                else:
                    delay_match = re.search(r"retry in (\d+\.?\d*)s", msg, re.IGNORECASE)
                    wait = f" Try again in {int(float(delay_match.group(1)))} seconds." if delay_match else ""
                    self._summary_error.emit(f"API rate limit hit.{wait} Please wait and try again.")
            else:
                self._summary_error.emit(f"Error: {msg[:200]}")

    def _on_summary_ready(self, text: str):
        """Handle successful summary generation (runs on UI thread)."""
        self._is_generating_summary = False
        self.summary_btn.setEnabled(True)
        self.summary_btn.setText("📋 Generate Summary")
        self.summary_text.setPlainText(text)

    def _on_summary_error(self, error_msg: str):
        """Handle summary generation error (runs on UI thread)."""
        self._is_generating_summary = False
        self.summary_btn.setEnabled(True)
        self.summary_btn.setText("📋 Generate Summary")
        self.summary_text.setPlainText(f"⚠️ {error_msg}")

    # ── Enrich key events ────────────────────────────────────────────────

    def _on_enrich_key_events(self):
        """Handle Enrich Key Events button — runs batch enrichment."""
        if self._is_enriching:
            return

        if not self._all_race_events:
            return

        settings = get_settings()
        api_key = settings.groq_api_key
        if not api_key:
            self.summary_text.setPlainText(
                "⚠️ No Groq API key configured. Go to Settings to add your key."
            )
            self.summary_panel.setVisible(True)
            return

        self._is_enriching = True
        self.enrich_btn.setEnabled(False)
        self.enrich_btn.setText("⏳ Enriching…")
        self.summary_btn.setEnabled(False)
        self.enrich_progress.setVisible(True)
        self.enrich_progress.setValue(0)

        events_copy = self._all_race_events
        frames_sample = []
        if self._all_frames:
            frames_sample.append(self._all_frames[0])
            for i in range(50, len(self._all_frames), 50):
                frames_sample.append(self._all_frames[i])
            frames_sample.append(self._all_frames[-1])

        thread = threading.Thread(
            target=self._enrich_thread,
            args=(events_copy, frames_sample, api_key, settings.ai_model),
            daemon=True,
        )
        thread.start()

    def _enrich_thread(self, events, frames, api_key, model):
        """Background thread: run batch enrichment and emit progress signals."""
        try:
            from src.insights.ai_commentary_engine import AICommentaryEngine
            engine = AICommentaryEngine(
                api_key=api_key,
                model=model or "llama-3.3-70b-versatile"
            )

            def on_progress(batch_done, total_batches, enriched):
                self._enrich_progress.emit(batch_done, total_batches, enriched)

            stats = engine.enrich_key_events(events, frames,
                                             progress_callback=on_progress)
            self._enrich_done.emit(stats)
        except Exception as e:
            msg = str(e)
            if "429" in msg or "RESOURCE_EXHAUSTED" in msg:
                import re
                if "PerDay" in msg or "limit: 20" in msg or "limit: 0" in msg:
                    self._enrich_error.emit(
                        "Daily API quota reached. Wait until tomorrow or enable billing."
                    )
                else:
                    delay_match = re.search(r"retry in (\d+\.?\d*)s", msg, re.IGNORECASE)
                    wait = f" Try again in {int(float(delay_match.group(1)))}s." if delay_match else ""
                    self._enrich_error.emit(f"Rate limit hit.{wait}")
            else:
                self._enrich_error.emit(f"Error: {msg[:150]}")

    def _on_enrich_progress(self, batch_done: int, total_batches: int, enriched: int):
        """Update progress bar during enrichment."""
        pct = int((batch_done / max(total_batches, 1)) * 100)
        self.enrich_progress.setMaximum(100)
        self.enrich_progress.setValue(pct)
        self.enrich_btn.setText(f"⏳ Batch {batch_done}/{total_batches}…")

    def _on_enrich_done(self, stats: dict):
        """Handle enrichment completion — refresh event cards."""
        self._is_enriching = False
        self.enrich_btn.setEnabled(True)
        self.enrich_btn.setText("✨ Enrich Key Events")
        self.summary_btn.setEnabled(True)
        self.enrich_progress.setVisible(False)

        # Refresh all event cards to show updated ai_commentary text
        for card in self._event_widgets:
            card.refresh_commentary()

        n = stats.get("enriched", 0)
        calls = stats.get("api_calls", 0)
        skipped = stats.get("skipped", 0)
        print(f"Enrichment done: {n} events enriched in {calls} API calls, "
              f"{skipped} low-priority events kept template commentary")

    def _on_enrich_error(self, error_msg: str):
        """Handle enrichment error."""
        self._is_enriching = False
        self.enrich_btn.setEnabled(True)
        self.enrich_btn.setText("✨ Enrich Key Events")
        self.summary_btn.setEnabled(True)
        self.enrich_progress.setVisible(False)
        self.summary_text.setPlainText(f"⚠️ Enrichment failed: {error_msg}")
        self.summary_panel.setVisible(True)


# ── Standalone launch ────────────────────────────────────────────────────

def main():
    app = QApplication(sys.argv)
    win = AICommentaryWindow()
    win.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
